language: python
python:
  - 2.7
notifications:
  email: false

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/miniconda
  - export PATH=~/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt
  - python setup.py install

# Run tests
script:
  - flake8 safeopt --exclude test*.py,__init__.py --ignore=E402,E731,W503 --show-source
  - flake8 safeopt --filename=__init__.py,test*.py --ignore=F,E402,W503 --show-source
  - pytest --doctest-modules --cov --cov-fail-under=50 safeopt

